### ISSUE TITLE
Create epub version

### ISSUE THREAD

**Issue by xmha97** [GoFarsi/book#128]
Please make a epub version. ممنون

**Comment by Ja7ad** [comment]
> Please make a epub version. ممنون

فعلا برنامه و شرایطی برای ایجاد نسخه های PDF, epub و سایر را نداریم اما در عوض می توانید از نسخه های آفلاینی که برای پلت فرم های مختلف قرار دادیم استفاده کنید.

برای نسخه های متنی نیازمند تجربه با Latex هست و اگر کسی مایل بود خوشحال میشیم از تجربه اش استفاده کنیم.

**Comment by xmha97** [comment]
ممنون که برای پلتفرم‌های مختلف اپلیکیشن منتشر کردید اما فکر می‌کنم این کار درد و سر اضافی بود و اگه یه PDF منتشر می‌کردید، کاربردی‌تر بود.

نکته‌ی بعدی اینه که من می‌تواهم این کتاب را بر روی e-book reader ام بخوانم که امکان نصب اپلیکیشن بر روی آن وجود ندارد.

و آخرین نکته اینه که من نسخه‌ی اندروید برنامه‌تون رو بر گوی موبایلم تست کردم و وارد نشد!
چه بدون اینترنت، چه با اینترنت، چه با اینترنت آزاد (فیلترشکن)
![Screenshot_2022-12-30-00-30-07-272_com.gofarsi.book.jpg](https://user-images.githubusercontent.com/23485114/210011180-2a9b9829-85e8-4c89-8f3a-4c7e5ff45ff8.jpg)
نمی‌دونم برنامه چگونه کار می‌کند اما پیشنهاد می‌کنم برنامه را طوری طراحی کنید که اصلا به اینترنت نیازی نداشته باشد که همیشه و در همه‌جا کار کند.
با تشکر از شما.

**Comment by Ja7ad** [comment]
احتمالا نسخه آفلاینش کنیم

**Comment by Ja7ad** [comment]
@xmha97 

لطفا آموزش زیر را بررسی کنید :

https://github.com/GoFarsi/book/wiki/%D8%A2%D9%85%D9%88%D8%B2%D8%B4-%D8%A7%D8%B3%D8%AA%D9%81%D8%A7%D8%AF%D9%87-%D8%A7%D8%B2-%D9%86%D8%B3%D8%AE%D9%87-%D8%A2%D9%81%D9%84%D8%A7%DB%8C%D9%86-%DA%A9%D8%AA%D8%A7%D8%A8#%D8%B3%DB%8C%D8%B3%D8%AA%D9%85-%D8%B9%D8%A7%D9%85%D9%84-%D8%A7%D9%86%D8%AF%D8%B1%D9%88%DB%8C%D8%AF

**Comment by xmha97** [comment]
ممنون، ایده‌ی جالبی بود.
