### ISSUE TITLE
QUIC protocol

### ISSUE THREAD

**Issue by kehiy** [GoFarsi/book#253]
hi!
i'm trying to write the QUIC protocol server chapter in network programming.
but there is an important question can I use go-quic package or we should implement the QUIC protocol from scratch ?

**Comment by Ja7ad** [comment]
> hi!
> i'm trying to write the QUIC protocol server chapter in network programming.
> but there is an important question can I use go-quic package or we should implement the QUIC protocol from scratch ?

We use package

**Comment by kehiy** [comment]
> > hi!
> > i'm trying to write the QUIC protocol server chapter in network programming.
> > but there is an important question can I use go-quic package or we should implement the QUIC protocol from scratch ?
> 
> We use package

thank you!
I will write this chapter ASAP.
