### ISSUE TITLE
سرفصل اول : slice

### ISSUE THREAD

**Issue by Ja7ad** [GoFarsi/book#33]

**Comment by Miraddo** [comment]
لیست بخش slices

- [ ] تعریف Slice
- [ ] استفاده از append
- [ ] استفاده از len

**Comment by Ja7ad** [comment]
@Miraddo نحوه انتخاب بخشی از slice
slice bytes
حذف یک element از slice
تابع copy
نحوه sort slice

**Comment by Miraddo** [comment]
transferred to => https://github.com/GoFarsi/book/issues/32
