### ISSUE TITLE
سرفصل اول : map

### ISSUE THREAD

**Issue by Ja7ad** [GoFarsi/book#34]

**Comment by Miraddo** [comment]
لیست بخش map

- [ ] تعریف map
- [ ] استفاده از make
- [ ] مقدار دهی map
- [ ] استفاده از delete

**Comment by ar-mokhtari** [comment]
- [x] مقدمه
- [ ] تعریف
- [ ] مقداردهی اولیه
- [ ] عملیات CRUD روی مپ
- [ ] پیمایش روی مپ
- [ ] خودآزمون
`تکمیل و اصلاح می‌گردد`
