### ISSUE TITLE
سرفصل اول :  اضافه کردن پکیج در کد

### ISSUE THREAD

**Issue by Ja7ad** [GoFarsi/book#37]

**Comment by Miraddo** [comment]
لیست بخش پکیج ها

- [ ] گو ماژول چیست ؟
- [ ] تعریف پروژه
- [ ] اضافه کردن third-party دپندنسی
- [ ] درباره Module Mirrors چه میدانید؟
- [ ] دیتابیس checksum
- [ ] تعریف Vendoring
- [ ] الگوریتم MVS
- [ ] به روز رسانی دپندنسی (Upgrade Dependency)

**Comment by Ja7ad** [comment]
@Miraddo میلاد جان این سر فصل در خصوص package level ها هستش بحث go mod تو سرفصل مباحث پیشرفته گذاشتیم
