### ISSUE TITLE
تکمیل بخش پیشگفتار

### ISSUE THREAD

**Issue by Ja7ad** [GoFarsi/book#5]

**Comment by ar-mokhtari** [comment]
معمولاً بخش پیش‌گفتار به «چرایی» و «چگونگی» نگارش کتاب می‌پردازه. 
در چرایی نگارش این کتاب می‌شه به عناوین زیر اشاره و پرداخته بشه:

1. چرا از گو استفاده می‌کنیم؟
2. شناخت نیازمندی و ابزارهای پیاده‌سازی وابسته به آن.
3. انواع منابع موجود جهت کسب اطلاعات و مقایسه‌ی آنها.
4. بررسی وضعیت منابع فارسی زبان گو در زمان تهیه این کتاب.

برای چگونگی نگارش کتاب می‌توان به موارد زیر اشاره کرد:
1. چگونه از جامعه تخصصی، می‌توان در آموزش،بهینه‌سازی و رشد دانش متقاضیان این تخصص استفاده کرد.
2. چرخ را از نو نسازیم، تجربه‌ها را از نو «تجربه» نکنیم، آموزش ببینیم و آموزش بدهیم.
3. «کلمات» قدرت دارند. به درک و استفاده از کلمات احترام بگذاریم. در جامعه تخصصی حتی چند‌برابر !!! 
4. دانش امروز، در هر رشته و هر سطح برآیند «انتقال» پیشینیان ما هست. بجای غرور ناشی از آن می‌توان از انتقال با احترام آن به دیگران لذت برد.
5. کار تیمی، به فرهنگ «با هم کار کردن» نیازمند هست.


... اصلاح و تکمیل می‌شود ...
